export const Permissions = {
  USER_CREATE: "user.create",
  USER_READ: "user.read",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",
  ROLE_READ: "role.read",
  ROLE_MANAGE: "role.manage",
  EMPLOYEE_CREATE: "employee.create",
  EMPLOYEE_READ: "employee.read",
  EMPLOYEE_UPDATE: "employee.update",
  EMPLOYEE_DELETE: "employee.delete",
  EMPLOYEE_EXPORT: "employee.export",
  CATEGORY_CREATE: "category.create",
  CATEGORY_READ: "category.read",
  CATEGORY_UPDATE: "category.update",
  CATEGORY_DELETE: "category.delete",
  SUB_CATEGORY_CREATE: "sub_category.create",
  SUB_CATEGORY_READ: "sub_category.read",
  SUB_CATEGORY_UPDATE: "sub_category.update",
  SUB_CATEGORY_DELETE: "sub_category.delete",
  SUB_SUB_CATEGORY_CREATE: "sub_sub_category.create",
  SUB_SUB_CATEGORY_READ: "sub_sub_category.read",
  SUB_SUB_CATEGORY_UPDATE: "sub_sub_category.update",
  SUB_SUB_CATEGORY_DELETE: "sub_sub_category.delete",
  PAYMENT_METHOD_CREATE: "payment_method.create",
  PAYMENT_METHOD_READ: "payment_method.read",
  PAYMENT_METHOD_UPDATE: "payment_method.update",
  PAYMENT_METHOD_DELETE: "payment_method.delete",
  EMPLOYEE_EXPENSE_READ: "employee_expense.read",
  EMPLOYEE_EXPENSE_UPDATE: "employee_expense.update",
  EMPLOYEE_EXPENSE_DELETE: "employee_expense.delete",
  EMPLOYEE_EXPENSE_APPROVE: "employee_expense.approve",
  SUPPLIER_CREATE: "supplier.create",
  SUPPLIER_READ: "supplier.read",
  SUPPLIER_UPDATE: "supplier.update",
  SUPPLIER_DELETE: "supplier.delete",
  CUSTOMER_CREATE: "customer.create",
  CUSTOMER_READ: "customer.read",
  CUSTOMER_UPDATE: "customer.update",
  CUSTOMER_DELETE: "customer.delete",
  PAYABLE_CREATE: "payable.create",
  PAYABLE_READ: "payable.read",
  PAYABLE_UPDATE: "payable.update",
  PAYABLE_DELETE: "payable.delete",
  PAYABLE_PAY: "payable.pay",
  RECEIVABLE_CREATE: "receivable.create",
  RECEIVABLE_READ: "receivable.read",
  RECEIVABLE_UPDATE: "receivable.update",
  RECEIVABLE_DELETE: "receivable.delete",
  RECEIVABLE_RECEIVE: "receivable.receive",
} as const;

/** Finance permissions added after the initial release (see the add-finance-permissions migration). */
export const FinancePermissions = [
  Permissions.EMPLOYEE_EXPENSE_APPROVE,
  Permissions.SUPPLIER_CREATE,
  Permissions.SUPPLIER_READ,
  Permissions.SUPPLIER_UPDATE,
  Permissions.SUPPLIER_DELETE,
  Permissions.CUSTOMER_CREATE,
  Permissions.CUSTOMER_READ,
  Permissions.CUSTOMER_UPDATE,
  Permissions.CUSTOMER_DELETE,
  Permissions.PAYABLE_CREATE,
  Permissions.PAYABLE_READ,
  Permissions.PAYABLE_UPDATE,
  Permissions.PAYABLE_DELETE,
  Permissions.PAYABLE_PAY,
  Permissions.RECEIVABLE_CREATE,
  Permissions.RECEIVABLE_READ,
  Permissions.RECEIVABLE_UPDATE,
  Permissions.RECEIVABLE_DELETE,
  Permissions.RECEIVABLE_RECEIVE,
] as const;

export type PermissionName = (typeof Permissions)[keyof typeof Permissions];

export const DefaultRolePermissions: Record<string, PermissionName[]> = {
  SUPER_ADMIN: Object.values(Permissions),
  ADMIN: [
    Permissions.USER_CREATE,
    Permissions.USER_READ,
    Permissions.USER_UPDATE,
    Permissions.USER_DELETE,
    Permissions.ROLE_READ,
    Permissions.EMPLOYEE_CREATE,
    Permissions.EMPLOYEE_READ,
    Permissions.EMPLOYEE_UPDATE,
    Permissions.EMPLOYEE_DELETE,
    Permissions.EMPLOYEE_EXPORT,
    Permissions.CATEGORY_CREATE,
    Permissions.CATEGORY_READ,
    Permissions.CATEGORY_UPDATE,
    Permissions.CATEGORY_DELETE,
    Permissions.SUB_CATEGORY_CREATE,
    Permissions.SUB_CATEGORY_READ,
    Permissions.SUB_CATEGORY_UPDATE,
    Permissions.SUB_CATEGORY_DELETE,
    Permissions.SUB_SUB_CATEGORY_CREATE,
    Permissions.SUB_SUB_CATEGORY_READ,
    Permissions.SUB_SUB_CATEGORY_UPDATE,
    Permissions.SUB_SUB_CATEGORY_DELETE,
    Permissions.PAYMENT_METHOD_CREATE,
    Permissions.PAYMENT_METHOD_READ,
    Permissions.PAYMENT_METHOD_UPDATE,
    Permissions.PAYMENT_METHOD_DELETE,
    Permissions.EMPLOYEE_EXPENSE_READ,
    Permissions.EMPLOYEE_EXPENSE_UPDATE,
    Permissions.EMPLOYEE_EXPENSE_DELETE,
    ...FinancePermissions,
  ],
  EDITOR: [Permissions.USER_READ],
  USER: [],
};
